import React from 'react';

const page = () => {
    return (
        <div className="max-w-container px-[10px] mx-auto py-[100px]">
            <h2 className='text-6xl my-5 font-semibold'>
                Commission Policy
            </h2>

            <p className='my-10'>At TIZARA, we believe in transparent and fair pricing to ensure our clients fully understand the costs associated with our services. Our commission policy is structured to align with our commitment to providing exceptional value while maintaining clarity for our investors:</p>
            <div className='flex flex-col gap-8'>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Management Fees
                    </h2>
                    <p>We charge a competitive management fee based on the assets under management (AUM) within our investment portfolios.<br />
                        The management fee is calculated as a percentage of the total value of your invested assets and is assessed periodically (e.g., monthly, or quarterly).</p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Performance-Based Fees
                    </h2>
                    <p>In addition to management fees, we may employ a performance-based fee structure. This fee is contingent upon achieving predefined performance benchmarks and aims to align our success with yours.
                        Performance-based fees, if applicable, are calculated as a percentage of the net profits generated by your investments above a specified benchmark or hurdle rate.</p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Trading and Transaction Fees
                    </h2>
                    <p>Depending on the investment products utilized, there might be trading and transaction fees associated with executing trades or rebalancing portfolios.
                        These fees cover the costs incurred from executing trades on various cryptocurrency exchanges and are transparently communicated before any transactions.
                    </p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Custodial and Administrative Fees
                    </h2>
                    <p>Certain investments may involve custodial or administrative fees charged by third-party service providers. These fees are passed on to investors and are outlined clearly in the investment documentation.
                    </p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Fee Structure Transparency
                    </h2>
                    <p>We are committed to providing complete transparency regarding our fee structure. Our clients receive comprehensive breakdowns of all fees associated with their investments in regular reports.
                    </p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        No Hidden Charges
                    </h2>
                    <p>At TIZARA, we do not believe in hidden charges or unexpected costs. We ensure that all fees are disclosed upfront, allowing our clients to make informed investment decisions.
                    </p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Customized Solutions
                    </h2>
                    <p>Depending on the investment strategy or products chosen, fee structures may vary. Our team works with clients to tailor investment solution
                    </p>
                </div>
                <div>
                    <h2 className='text-3xl font-semibold'>
                        Review and Consultation
                    </h2>
                    <p>We encourage our clients to schedule periodic reviews and consultations with our team to discuss their investment performance, fee structure, and any queries or concerns they may have.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default page;